---

- name: Start management UI
  command: /usr/lib/rabbitmq/bin/rabbitmq-plugins enable rabbitmq_management

- name: Restart RabbitMQ server
  service:
    name: rabbitmq-server
    state: restarted

- wait_for:
    port: 15672

- name: Allow port 15672
  shell: iptables -I INPUT -p tcp --dport 15672 -m state --state NEW,ESTABLISHED -j ACCEPT